language: android
dist: trusty

install:
    - echo yes | android update sdk --no-ui --force > /dev/null
    - echo yes | android update sdk --no-ui --force > /dev/null
    - echo yes | android update sdk --all --no-ui --force > /dev/null
    - ./gradlew assemble
    - ./gradlew assembleAndroidTest
    - ls app/build/outputs/apk
script:
    - echo "HEllo world"
